project:
  type: website

website:
  title: "log"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - icon: moon
        href: "#"
        aria-label: Dark mode
        id: quarto-dark-toggle
  repo-url: https://github.com/tokenbender/log
  repo-actions: [edit, issue]

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true

execute:
  freeze: auto



